const $=s=>document.querySelector(s);const canvas=$('#preview'),ctx=canvas.getContext('2d',{alpha:true});const el={sheetInput:$('#sheetInput'),dropZone:$('#dropZone'),assetName:$('#assetName'),animationName:$('#animationName'),direction:$('#direction'),frameCount:$('#frameCount'),layout:$('#layout'),frameWidth:$('#frameWidth'),frameHeight:$('#frameHeight'),fps:$('#fps'),fpsLabel:$('#fpsLabel'),detectButton:$('#detectButton'),outputWidth:$('#outputWidth'),outputHeight:$('#outputHeight'),anchor:$('#anchor'),spriteScale:$('#spriteScale'),scaleLabel:$('#scaleLabel'),removeBlack:$('#removeBlack'),blackTolerance:$('#blackTolerance'),toleranceLabel:$('#toleranceLabel'),previewTitle:$('#previewTitle'),targetPath:$('#targetPath'),timeline:$('#timeline'),sheetInfo:$('#sheetInfo'),emptyPreview:$('#emptyPreview'),playButton:$('#playButton'),exportFrame:$('#exportFrame'),exportKit:$('#exportKit'),exportKitSide:$('#exportKitSide'),exportManifest:$('#exportManifest'),newProject:$('#newProject'),zoomIn:$('#zoomIn'),zoomOut:$('#zoomOut'),zoomLabel:$('#zoomLabel')};
const state={image:null,file:null,frame:0,playing:false,timer:null,zoom:4};
const cleanName=v=>String(v||'sprite').trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'')||'sprite';
const clamp=(v,min,max,fb)=>{v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):fb};
function settings(){return{name:cleanName(el.assetName.value),animation:el.animationName.value,direction:el.direction.value,count:clamp(el.frameCount.value,1,64,1),layout:el.layout.value,fw:clamp(el.frameWidth.value,1,4096,64),fh:clamp(el.frameHeight.value,1,4096,64),fps:clamp(el.fps.value,1,30,10),ow:clamp(el.outputWidth.value,8,512,64),oh:clamp(el.outputHeight.value,8,512,64),anchor:el.anchor.value,scale:clamp(el.spriteScale.value,10,400,100)/100,removeBlack:el.removeBlack.checked,tolerance:clamp(el.blackTolerance.value,0,100,20)}}
function autoDetect(){if(!state.image)return;const w=state.image.naturalWidth,h=state.image.naturalHeight;let horizontal=w>=h;let count=Math.max(1,Math.round(horizontal?w/h:h/w));if(horizontal&&w%count!==0){const likely=[4,6,8,10,12,16].find(n=>w/n>=32&&w/n<=512);if(likely)count=likely}el.layout.value=horizontal?'horizontal':'vertical';el.frameCount.value=count;el.frameWidth.value=Math.floor(horizontal?w/count:w);el.frameHeight.value=Math.floor(horizontal?h:h/count);state.frame=0;sync()}
async function loadFile(file){if(!file||!['image/png','image/webp'].includes(file.type)){alert('Escolha uma imagem PNG ou WebP.');return}const url=URL.createObjectURL(file),img=new Image();img.decoding='async';await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url}).catch(()=>null);if(!img.naturalWidth){URL.revokeObjectURL(url);alert('Não foi possível abrir a imagem.');return}if(state.image?.src?.startsWith('blob:'))URL.revokeObjectURL(state.image.src);state.image=img;state.file=file;el.emptyPreview.hidden=true;autoDetect()}
function sourceRect(i,s){return s.layout==='horizontal'?{x:i*s.fw,y:0,w:s.fw,h:s.fh}:{x:0,y:i*s.fh,w:s.fw,h:s.fh}}
function placement(s){const dw=s.fw*s.scale,dh=s.fh*s.scale;if(s.anchor==='center')return{x:(s.ow-dw)/2,y:(s.oh-dh)/2,w:dw,h:dh};if(s.anchor==='top-left')return{x:0,y:0,w:dw,h:dh};return{x:(s.ow-dw)/2,y:s.oh-dh,w:dw,h:dh}}
function rawFrame(i,s){const c=document.createElement('canvas');c.width=s.fw;c.height=s.fh;const x=c.getContext('2d',{willReadFrequently:s.removeBlack});x.imageSmoothingEnabled=false;const r=sourceRect(i,s);x.drawImage(state.image,r.x,r.y,r.w,r.h,0,0,s.fw,s.fh);if(s.removeBlack){const d=x.getImageData(0,0,c.width,c.height),t=s.tolerance*2.55;for(let p=0;p<d.data.length;p+=4){if(d.data[p]<=t&&d.data[p+1]<=t&&d.data[p+2]<=t)d.data[p+3]=0}x.putImageData(d,0,0)}return c}
function finalFrame(i,s=settings()){const out=document.createElement('canvas');out.width=s.ow;out.height=s.oh;const x=out.getContext('2d');x.imageSmoothingEnabled=false;const raw=rawFrame(i,s),p=placement(s);x.drawImage(raw,p.x,p.y,p.w,p.h);return out}
function render(){const s=settings();canvas.width=s.ow;canvas.height=s.oh;canvas.style.width=`${s.ow*state.zoom}px`;canvas.style.height=`${s.oh*state.zoom}px`;ctx.clearRect(0,0,s.ow,s.oh);ctx.imageSmoothingEnabled=false;if(state.image)ctx.drawImage(finalFrame(state.frame,s),0,0);el.fpsLabel.textContent=`${s.fps} FPS`;el.scaleLabel.textContent=`${Math.round(s.scale*100)}%`;el.toleranceLabel.textContent=s.tolerance;el.zoomLabel.textContent=`${state.zoom*100}%`;el.previewTitle.textContent=`${s.name} · ${s.animation} · ${s.direction}`;el.targetPath.textContent=`public/assets/${s.ow}/creatures/${s.name}/`;el.sheetInfo.textContent=state.image?`${state.image.naturalWidth}×${state.image.naturalHeight}px · ${s.count} frames · ${s.fw}×${s.fh}px cada`:'Nenhuma imagem carregada';renderTimeline(s)}
function renderTimeline(s){el.timeline.innerHTML='';if(!state.image)return;for(let i=0;i<s.count;i++){const b=document.createElement('button');b.className='frame-card'+(i===state.frame?' active':'');const c=finalFrame(i,s);c.width=s.ow;c.height=s.oh;b.append(c);const label=document.createElement('span');label.textContent=`Frame ${i+1}`;b.append(label);b.onclick=()=>{state.frame=i;render()};el.timeline.append(b)}}
function sync(){const s=settings();state.frame=Math.min(state.frame,s.count-1);render();if(state.playing)startPlayback()}
function startPlayback(){stopPlayback(false);state.playing=true;el.playButton.textContent='⏸ Pausar';const step=()=>{const s=settings();state.frame=(state.frame+1)%s.count;render()};state.timer=setInterval(step,1000/settings().fps)}
function stopPlayback(change=true){if(state.timer)clearInterval(state.timer);state.timer=null;if(change){state.playing=false;el.playButton.textContent='▶ Reproduzir'}}
function togglePlayback(){state.playing?stopPlayback():startPlayback()}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),500)}
function canvasBlob(c){return new Promise(r=>c.toBlob(r,'image/png'))}
function manifest(s=settings()){return{schema:'gamerpg.sprite-kit.v1',id:s.name,type:'creature',basePath:`public/assets/${s.ow}/creatures/${s.name}/`,frame:{width:s.ow,height:s.oh,anchor:s.anchor},animations:{[s.animation]:{[s.direction]:{sheet:`${s.animation}_${s.direction}.png`,frames:s.count,fps:s.fps,loop:s.animation!=='death'}}},source:{file:state.file?.name||null,frameWidth:s.fw,frameHeight:s.fh,layout:s.layout}}}
async function exportCurrent(){if(!state.image)return alert('Importe uma spritesheet primeiro.');const s=settings(),blob=await canvasBlob(finalFrame(state.frame,s));downloadBlob(blob,`${s.name}_${s.animation}_${s.direction}_${state.frame+1}.png`)}
async function exportManifest(){const s=settings(),blob=new Blob([JSON.stringify(manifest(s),null,2)],{type:'application/json'});downloadBlob(blob,'manifest.json')}
async function exportKit(){if(!state.image)return alert('Importe uma spritesheet primeiro.');if(!window.JSZip)return alert('O componente ZIP não carregou. Atualize a página e tente novamente.');const s=settings(),zip=new JSZip(),root=zip.folder(`${s.name}`),frames=root.folder('frames'),sheet=document.createElement('canvas');sheet.width=s.ow*s.count;sheet.height=s.oh;const sx=sheet.getContext('2d');sx.imageSmoothingEnabled=false;for(let i=0;i<s.count;i++){const f=finalFrame(i,s);sx.drawImage(f,i*s.ow,0);frames.file(`${s.animation}_${s.direction}_${String(i+1).padStart(2,'0')}.png`,await canvasBlob(f))}root.file(`${s.animation}_${s.direction}.png`,await canvasBlob(sheet));root.file('manifest.json',JSON.stringify(manifest(s),null,2));root.file('INSTALL.txt',`Copie esta pasta para:\npublic/assets/${s.ow}/creatures/${s.name}/\n\nSpritesheet: ${s.animation}_${s.direction}.png\nFrames: ${s.count}\nFPS: ${s.fps}\nTamanho do frame: ${s.ow}x${s.oh}\nÂncora: ${s.anchor}\n`);const blob=await zip.generateAsync({type:'blob'});downloadBlob(blob,`${s.name}-gamerpg-kit.zip`)}
function reset(){stopPlayback();state.frame=0;state.image=null;state.file=null;el.sheetInput.value='';el.assetName.value='warrior';el.animationName.value='run';el.direction.value='south';el.frameCount.value=6;el.frameWidth.value=64;el.frameHeight.value=64;el.outputWidth.value=64;el.outputHeight.value=64;el.emptyPreview.hidden=false;render()}
[el.assetName,el.animationName,el.direction,el.frameCount,el.layout,el.frameWidth,el.frameHeight,el.fps,el.outputWidth,el.outputHeight,el.anchor,el.spriteScale,el.removeBlack,el.blackTolerance].forEach(x=>x.addEventListener('input',sync));el.sheetInput.addEventListener('change',e=>loadFile(e.target.files[0]));el.detectButton.onclick=autoDetect;el.playButton.onclick=togglePlayback;el.exportFrame.onclick=exportCurrent;el.exportKit.onclick=exportKit;el.exportKitSide.onclick=exportKit;el.exportManifest.onclick=exportManifest;el.newProject.onclick=reset;el.zoomIn.onclick=()=>{state.zoom=Math.min(12,state.zoom+1);render()};el.zoomOut.onclick=()=>{state.zoom=Math.max(1,state.zoom-1);render()};['dragenter','dragover'].forEach(n=>el.dropZone.addEventListener(n,e=>{e.preventDefault();el.dropZone.classList.add('dragging')}));['dragleave','drop'].forEach(n=>el.dropZone.addEventListener(n,e=>{e.preventDefault();el.dropZone.classList.remove('dragging')}));el.dropZone.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));render();